### ISSUE TITLE
IE9 issue. Unable to get property 'add' of undefined or null reference

### ISSUE THREAD

**Issue by synthview** [bespokejs/bespoke#23]
Hello,
I've put your bespoke.js + the js you've used on your demo page on my page but I have this error with IE9-

Unable to get property 'add' of undefined or null reference
on the line:
el.classList.add(moduleName + '-' + cls);

any idea?

**Comment by ebrahimsblog** [comment]
it worked!! Many thanks!

**Comment by jerfink** [comment]
perfect
