### ISSUE TITLE
Destroy a Slide Deck

### ISSUE THREAD

**Issue by LucyintheSkyWithDiamonds** [bespokejs/bespoke#65]
Sorry if I am missing something here, but after creating a deck, how do I destroy it?

If not already possible, can you add that as a method or advise how I would go about it? Would removing all the bespoke type classes from the specific area of the DOM suffice?

**Comment by hsablonniere** [comment]
What's your use case? What do you want to restore?

**Comment by mojavelinux** [comment]
The destroy method is now available. It fires the destroy event, then unregisters all listeners. If additional functionality is needed, please open a new issue with specifics.
